cataloguer_configuration:
    bucket_name: "ekstepspeechrecognition-dev"
    source_landing_path: "data/audiotospeech/raw/download/downloaded/hindi/audio/"
    error_landing_path: "data/audiotospeech/raw/download/catalogued/hindi/audio/error/"
    landing_path: "data/audiotospeech/raw/download/catalogued/hindi/audio/"

db_configuration:
    db_name: ''
    db_pass: ''
    db_user: ''
    cloud_sql_connection_name: ''
