# sample configeration
config:
  common:
    db_configuration:
        db_name: ''
        db_pass: ''
        db_user: ''
        cloud_sql_connection_name: ''

    gcs_config:
      # master data bucket for ekstep
      master_bucket: ''

    azure_transcription_client:
      speech_key: ''
      service_region: ''

    google_transcription_client:
      language: ''
      sample_rate: ''
      audio_channel_count: ''

  data_tagger_config:
    # path of to the folder in the master bucket where the data tagger will move the data to
    landing_directory_path: ''

    # path of to the folder in the master bucket from where the data tagger will pick up the data that needs to be moved
    source_directory_path: ''

    filter_criteria:

      filter_by_speaker_meta_data:
        number_of_speakers: 1
        number_of_minutes_per_speaker: 1
        source_name: ''

      filter_by_source:
        source: []

  audio_processor_config:
    # defaults to hi-IN
    language: ''

    # path of the files on gcs which need to be processed
    remote_raw_audio_file_path: ''

    snr_done_folder_path: ''

    # path where the processed files need to be uploaded
    remote_processed_audio_file_path: ''


    chunking_conversion_configeration:
      aggressiveness: ''
      max_duration: ''

    # SNR specific configeration
    snr_configeration:

      max_snr_threshold: ''
      local_input_file_path: ''
      local_output_file_path: ''

  audio_transcription_config:
    # defaults to hi-IN
    language: ''

    # path of the files on gcs which need to be processed for stt
    remote_clean_audio_file_path: ''

    # path where the processed files need to be uploaded
    remote_stt_audio_file_path: ''


