application:
  verbose: 0
  logging: 0
  language: 'hi'


downloader: ## data loader
  mode: 'video'
  tobeprocessed_input_basepath: 'data/audiotospeech/raw/tobeprocessed/hindi/audio/'
  local_data_path: ''
  convert_to_wav: True                       # convert audio file to wav
  output_wav_dir: null                       # output directory path for converted wav

srtgenerator:
  bin_size: 10                      # Bin size for generating srt files
  input_file_path: 'data/audiotospeech/raw/tobeprocessed/hindi/audio'               # input audio file path for generating SRT
  output_file_path: null            # Path where subtitles will be stored
  dump_response: True              # whether dump response in an external file
  dump_response_directory: null     # response dump directory

clipaudio:
  srt_file_path: ''                 # input SRT File path
  audio_file_path: ''               # input audio file path
  output_file_dir: 'data/audiotospeech/integration/processed/hindi/audio'        # output file directory


filtersnr:
  input_file_dir: null
  output_file_dir: null
  threshold: 20
