application:
  storage_type_input: 'local'     # possible values (local, gcp)
  storage_type_output: 'local'    # possible values (local, gcp)
  verbose: 0
  logging: 0
  credential_file_path: './credentials.json'
  bucket_path: 'gs://ekstepspeechrecognition-dev/'
  language: 'hi'


downloader: ## data loader
  link: 'https://www.youtube.com/playlist?list=PLoEiobi8_gm5tP_kUE9fzCAs7aK0OIIjw'                 # [*required](link, can be playlist, video link)
  output_dir_path: '/home/harveen.chadha/gcmount/data/audiotospeech/raw/landing/hindi/audio/testing'                  # output directory path 
  mode: 'playlist'                     # can be [video, playlist, videolist]
  filename_prefix: 'testing_playlist'        # filename prefix
  convert_to_wav: True              # convert audio file to wav
  output_wav_dir: null              # output directory path for converted wav


srtgenerator:
  bin_size: 10                      # Bin size for generating srt files
  input_file_path: ''               # input audio file path for generating SRT
  output_file_path: null            # Path where subtitles will be stored
  dump_response: False              # whether dump response in an external file
  dump_response_directory: null     # response dump directory

clipaudio:
  srt_file_path: ''                 # input SRT File path
  audio_file_path: ''               # input audio file path
  output_file_dir: '/home/harveen.chadha/gcmount/data/audiotospeech/raw/landing/hindi/audio/testing/cutaudio'        # output file directory


