configuration:
    num_speakers: 0
    duration_per_speaker: 100
    experiment_name: "test_with_multiple_speakers11"
    experiment_description: "speaker diversity"
    source: "sourceName"
    use_existing_experiment_data: False
    existing_experiment_name: "test_exp"
    number_of_speaker_from_existing_experiment: 0
    metadata_output_path: 'data/experiments/input'
    
source_data_config:
    using_source: True
    sources: []
    use_existing_source_data: True
    existing_source_name: ["testpipeline"]
    
bucket_configuration:
    bucket_name: "ekstepspeechrecognition-dev"
    integration_path: "data/audiotospeech/integration/processed/hindi/audio/"
    exp_output_path: "data/experiments/output/"

db_configuration:
    db_name: ''
    db_pass: ''
    db_user: ''
    cloud_sql_connection_name: ''
